spring:
  datasource:
    url: jdbc:mysql://117.174.24.6:3306/yun-util?characterEncoding=utf8&useSSL=false
    username: root
    password: skkj123

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database: mysql
    hibernate:
      #      ddl-auto: update # todo
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true

#  cache:
#    type: redis
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    password:

management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 10111
    servlet:
      context-path: /
    ssl:
      enabled: false
  endpoint:
    health:
      show-details: always