spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/yun-util?characterEncoding=utf8&useSSL=false
    username: root
    password: yun123

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database: mysql
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true

#  cache:
#    type: redis
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    password:
