spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/yun-util?characterEncoding=utf8&useSSL=false
    username: root
    password: yun123

  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false
    database: mysql
    hibernate:
      #      ddl-auto: update # todo
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false

#  cache:
#    type: redis
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    password:
